### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by dingo-d** [php-stubs/woocommerce-stubs#3]
I'm trying to add the WooCommerce stubs using `composer require --dev php-stubs/woocommerce-stubs` but I keep getting an error

```
Script PHPStan\WordPress\Composer\FixWpStubs::php73Polyfill handling the post-update-cmd event terminated with an exception

Installation failed, reverting ./composer.json to its original content.


  [ErrorException]
  file_get_contents(.../vendor/giacocorsiglia/
  wordpress-stubs/wordpress-stubs.php): failed to open stream: No such file or directory
```

Any idea why would this happen?

**Comment by szepeviktor** [comment]
> FixWpStubs::php73Polyfill

I think you have taken **all** of the example phpstan config file :)

**Comment by dingo-d** [comment]
my config file looks like this:

```
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
    excludes_analyse:
        - %rootDir%/../../../vendor/
        - %rootDir%/../../../node_modules/
        - %rootDir%/../../../bin/
        - %rootDir%/../../../src/Core/CompiledContainer.php
    autoload_files:
        - %currentWorkingDirectory%/vendor/autoload.php
    ignoreErrors:
        # Uses func_get_args()
        - '#Function apply_filters invoked with [34567] parameters, 2 required\.#'
        - '#Constant ASSETS_MANIFEST not found\.#'
```

When I removed vendor, lock and reinstalled it, without woocommerce stubs, it started working 🤷‍♂️  

Installing it, again, gives error

```bash
Using version ^4.1 for php-stubs/woocommerce-stubs
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Updating php-stubs/wordpress-stubs (v5.1.1 => v5.4.0): Downloading (100%)
  - Installing php-stubs/woocommerce-stubs (v4.1.0): Downloading (100%)
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Writing lock file
Generating optimized autoload files
Deprecation Notice: Class tad\WPBrowser\Configuration\Configuration located in ./vendor/lucatume/wp-browser/src/tad/WPBrowser/Environment/Configuration.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_CLI located in ./vendor/wp-cli/wp-cli/php/class-wp-cli.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_CLI_Command located in ./vendor/wp-cli/wp-cli/php/class-wp-cli-command.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
29 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> PHPStan\WordPress\Composer\FixWpStubs::php73Polyfill
Removing duplicate is_countable() ...
Script PHPStan\WordPress\Composer\FixWpStubs::php73Polyfill handling the post-update-cmd event terminated with an exception

Installation failed, reverting ./composer.json to its original content.


  [ErrorException]
  file_get_contents(/Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woo-solo-api/vendor/giacocorsiglia/
  wordpress-stubs/wordpress-stubs.php): failed to open stream: No such file or directory


require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```
